### PR TITLE
[Testing] Unit tests, E2E tests, logging and other Fixes / "Touchups"

### LINKED ISSUE #180: [Configs] Make `Genesis` staked `Actors` available via the `AccountKeeper`
## Objective

Make it more convenient to interact with the state of LocalNet/DevNet when it's restarted.

## Origin Document

Taken from #177:

Screenshot 2023-11-13 at 4 22 12 PM

We prepare `config.yml` for ignite to configure how to generate `genesis.json` by following the [specifications here](https://docs.ignite.com/references/config).

For example, the following `config.yml` configuration:

```yaml
accounts:
  - name: faucet
    mnemonic: "baby advance work soap slow exclude blur humble lucky rough teach wide chuckle captain rack laundry butter main very cannon donate armor dress follow"
    coins:
      - 999999999999999999upokt
```

Outputs the following `genesis.json` configuration:

```json
    "auth": {
      "params": {
        "max_memo_characters": "256",
        "tx_sig_limit": "7",
        "tx_size_cost_per_byte": "10",
        "sig_verify_cost_ed25519": "590",
        "sig_verify_cost_secp256k1": "1000"
      },
      "accounts": [
        {
          "@type": "/cosmos.auth.v1beta1.BaseAccount",
          "address": "pokt1awtlw5sjmw2f5lgj8ekdkaqezphgz88rdk93sk",
          "pub_key": null,
          "account_number": "0",
          "sequence": "0"
        },
```

However, we can see that the `AccountKeeper`, which uses the `accounts` field in the genesis file has a null `pub_key`, which translates to a null `pub_key` when querying it. For example:

```bash
$ poktrolld --home ./localnet/poktrolld/ q account pokt19a3t4yunp0dlpfjrp7qwnzwlrzd5fzs2gjaaaj --node tcp://127.0.0.1:36657
'@type': /cosmos.auth.v1beta1.BaseAccount
account_number: "6"
address: pokt1re27pw4llwnatx4sq7rlggqzcm6j3f39epq2wa
pub_key: null
sequence: "2"
```

However, after it has been interacted with, the `pub_key` is available:

```bash
$ poktrolld --home ./localnet/poktrolld/ q account pokt19a3t4yunp0dlpfjrp7qwnzwlrzd5fzs2gjaaaj --node tcp://127.0.0.1:36657
'@type': /cosmos.auth.v1beta1.BaseAccount
account_number: "6"
address: pokt1re27pw4llwnatx4sq7rlggqzcm6j3f39epq2wa
pub_key:
  '@type': /cosmos.crypto.secp256k1.PubKey
  key: ApSbBWHYHLOHkAdm4YKdccPzwSUKiWNhlUTd8IQVaH8a
sequence: "2"
```

## Goals

- Streamline the process of account management during re-genesis
- Make local development faster/easier without repetitive commands (e.g. staking actors) each time
- Enable us to have staked suppliers & regenesis during TestNet
- Start preparing for MainNet where we will need to have staked suppliers/applications when migrating

## Deliverables

- [ ] An investigation that determines the best way to achieve the result below. For example:
	- A script that manually (i.e. `sed`) updates `genesis.json` after re-genesis?
	- An update to [ignite](https://docs.ignite.com/references/config) that'll support `pub_keys` in config.yaml
	- Something else?
- [ ] A PR that updates the `make localnet_regenesis` target using the solution determined above
- [ ] If ignite was not updated, submitting an issue to [ignite/cli/iss](https://github.com/ignite/cli/issues) that documents this behaviour and request a new feature

## Non-goals / Non-deliverables

- Updating the genesis state (i.e. adding or removing new actors)
- Updating the ignite CLI binary ourselves

## General deliverables

- [ ] **Comments**: Add/update TODOs and comments alongside the source code so it is easier to follow.
- [ ] **Testing**: Add new tests (unit and/or E2E) to the test suite.
- [ ] **Makefile**: Add new targets to the Makefile to make the new functionality easier to use.
- [ ] **Documentation**: Update architectural or development READMEs; use [mermaid](https://mermaid-js.github.io/mermaid/) diagrams where appropriate.

---

**Creator**: @Olshansk 
**Co-Owners**: @h5law @okdas

### PR DESCRIPTION
**Pull request by Olshansk**
### Human Summary

This is aiming to fix multiple issues in E2E tests and just general QoL improvements:
1. Adding a comment in `relay.feature` about the need to run `make supplier1_stake && make app1_stake` until we fix #180 (known issue)
2. Replacing the reference to host `sequencer-poktroll-sequencer` with `localhost` (see first screenshot below)
3. Fixed a bug leading us to assert against a `MsgSubmitProof` event instead of a `MsgCreateClaim` event (see second screenshot below)
4. Fixed on-chain logging under `x/*` by replacing `logger\.(Info|Error)\("([^"]+)"(?:, (.*))?\)` with `logger.$1(fmt.Sprintf("$2", $3))` so it works as expected
5. Some quality-of-life comments & TODOs
6. Minor additions to unit tests from #220 

Reasoning for `s/sequencer-poktroll-sequencer/localhost`:
Screenshot 2023-12-09 at 8 39 08 PM

Unresolved yet:
Screenshot 2023-12-09 at 8 51 20 PM

### AI Summary

review pad:summary

## Issue

Improving the

## Type of change

Select one or more:

- [ ] New feature, functionality or library
- [x] Bug fix
- [ ] Code health or cleanup
- [ ] Documentation
- [ ] Other (specify)

## Testing

- [x] **Run all unit tests**: `make go_develop_and_test`
- [x] **Run E2E tests**: `make e2e_test`

## Sanity Checklist

- [x] I have tested my changes using the available tooling
- [x] I have performed a self-review of my own code
- [x] I have commented my code, updated documentation and left TODOs throughout the codebase

### CODE REVIEW

**Comment by Olshansk** [comment]
@okdas Seems like the change I made from `sequencer-poktroll-sequencer` to `localhost` works when I run `make test_e2e` locally but fails in CI. Either I'm missing something or we might have to add an environment variable to configure this, please let me know what you suggest! 

Screenshot 2023-12-10 at 4 25 46 PM

Screenshot 2023-12-10 at 4 25 23 PM

File: e2e/tests/session_steps_test.go [hunk 1]
```diff
@@ -11,20 +11,19 @@ import (
...
 	abci "github.com/cometbft/cometbft/abci/types"
-	"github.com/stretchr/testify/require"
-
 	"github.com/pokt-network/poktroll/pkg/client/events"
 	"github.com/pokt-network/poktroll/pkg/either"
 	"github.com/pokt-network/poktroll/pkg/observable"
 	"github.com/pokt-network/poktroll/pkg/observable/channel"
 	"github.com/pokt-network/poktroll/testutil/testclient"
 	suppliertypes "github.com/pokt-network/poktroll/x/supplier/types"
+	"github.com/stretchr/testify/require"
```
Comment (h5law) [inline e2e/tests/session_steps_test.go:20]: This should go back to the middle section as its not an internal import

File: testutil/testclient/testsupplier/client.go [hunk 2]
```diff
@@ -6,15 +6,14 @@ import (
...
-	"github.com/stretchr/testify/require"
-
 	"github.com/pokt-network/poktroll/pkg/client"
 	"github.com/pokt-network/poktroll/pkg/client/supplier"
 	"github.com/pokt-network/poktroll/pkg/client/tx"
 	"github.com/pokt-network/poktroll/testutil/mockclient"
 	"github.com/pokt-network/poktroll/testutil/testclient/testtx"
 	sessiontypes "github.com/pokt-network/poktroll/x/session/types"
+	"github.com/pokt-network/smt"
+	"github.com/stretchr/testify/require"
```
Comment (h5law) [inline testutil/testclient/testsupplier/client.go:16]: Same as https://github.com/pokt-network/poktroll/pull/253/files#r1423131221 maybe you should look into using `goimports-reviser` it should fix this sort of thing automatically for you

File: testutil/testclient/testtx/client.go [hunk 3]
```diff
@@ -8,15 +8,13 @@ import (
...
-
-	"github.com/pokt-network/poktroll/testutil/mockclient"
-
 	"github.com/pokt-network/poktroll/pkg/client"
 	"github.com/pokt-network/poktroll/pkg/client/tx"
 	"github.com/pokt-network/poktroll/pkg/either"
+	"github.com/pokt-network/poktroll/testutil/mockclient"
 	"github.com/pokt-network/poktroll/testutil/testclient/testblock"
 	"github.com/pokt-network/poktroll/testutil/testclient/testeventsquery"
+	"github.com/stretchr/testify/require"
```
Comment (h5law) [inline testutil/testclient/testtx/client.go:17]: https://github.com/pokt-network/poktroll/pull/253/files#r1423131221

File: x/application/keeper/msg_server_delegate_to_gateway_test.go [hunk 4]
```diff
@@ -5,13 +5,12 @@ import (
...
 
 	sdk "github.com/cosmos/cosmos-sdk/types"
-	"github.com/stretchr/testify/require"
-
 	keepertest "github.com/pokt-network/poktroll/testutil/keeper"
 	"github.com/pokt-network/poktroll/testutil/sample"
 	"github.com/pokt-network/poktroll/x/application/keeper"
 	"github.com/pokt-network/poktroll/x/application/types"
 	sharedtypes "github.com/pokt-network/poktroll/x/shared/types"
+	"github.com/stretchr/testify/require"
```
Comment (h5law) [inline x/application/keeper/msg_server_delegate_to_gateway_test.go:13]: https://github.com/pokt-network/poktroll/pull/253/files#r1423131221

File: x/application/keeper/msg_server_undelegate_from_gateway_test.go [hunk 5]
```diff
@@ -5,13 +5,12 @@ import (
...
 
 	sdk "github.com/cosmos/cosmos-sdk/types"
-	"github.com/stretchr/testify/require"
-
 	keepertest "github.com/pokt-network/poktroll/testutil/keeper"
 	"github.com/pokt-network/poktroll/testutil/sample"
 	"github.com/pokt-network/poktroll/x/application/keeper"
 	"github.com/pokt-network/poktroll/x/application/types"
 	sharedtypes "github.com/pokt-network/poktroll/x/shared/types"
+	"github.com/stretchr/testify/require"
```
Comment (h5law) [inline x/application/keeper/msg_server_undelegate_from_gateway_test.go:13]: https://github.com/pokt-network/poktroll/pull/253/files#r1423131221 starting to wonder why these are being moved...

File: x/session/keeper/session_hydrator.go [hunk 6]
```diff
@@ -9,11 +9,10 @@ import (
 
 	sdkerrors "cosmossdk.io/errors"
 	sdk "github.com/cosmos/cosmos-sdk/types"
-	_ "golang.org/x/crypto/sha3"
-
 	"github.com/pokt-network/poktroll/x/session/types"
 	sharedhelpers "github.com/pokt-network/poktroll/x/shared/helpers"
 	sharedtypes "github.com/pokt-network/poktroll/x/shared/types"
+	_ "golang.org/x/crypto/sha3"
```
Comment (h5law) [inline x/session/keeper/session_hydrator.go:15]: https://github.com/pokt-network/poktroll/pull/253/files#r1423131221 again this should be the middle section

File: x/supplier/client/cli/helpers_test.go [hunk 7]
```diff
@@ -27,6 +25,7 @@ import (
 	sharedtypes "github.com/pokt-network/poktroll/x/shared/types"
 	"github.com/pokt-network/poktroll/x/supplier/client/cli"
 	"github.com/pokt-network/poktroll/x/supplier/types"
+	"github.com/stretchr/testify/require"
```
Comment (h5law) [inline x/supplier/client/cli/helpers_test.go:28]: https://github.com/pokt-network/poktroll/pull/253/files#r1423131221

File: x/supplier/keeper/msg_server_submit_proof.go [hunk 8]
```diff
@@ -4,7 +4,6 @@ import (
 	"context"
 
 	sdk "github.com/cosmos/cosmos-sdk/types"
-
 	"github.com/pokt-network/poktroll/x/supplier/types"
```
Comment (h5law) [inline x/supplier/keeper/msg_server_submit_proof.go:7]:
```suggestion

	"github.com/pokt-network/poktroll/x/supplier/types"
```

File: x/supplier/keeper/msg_server_stake_supplier.go [hunk 9]
```diff
@@ -2,10 +2,10 @@ package keeper
 
 import (
 	"context"
+	"fmt"
 
 	sdkerrors "cosmossdk.io/errors"
 	sdk "github.com/cosmos/cosmos-sdk/types"
```
Comment (h5law) [inline x/supplier/keeper/msg_server_stake_supplier.go:8]:
```suggestion
	sdk "github.com/cosmos/cosmos-sdk/types"
	
```

File: x/supplier/keeper/claim.go [hunk 10]
```diff
@@ -2,10 +2,10 @@ package keeper
 
 import (
 	"encoding/binary"
+	"fmt"
 
 	"github.com/cosmos/cosmos-sdk/store/prefix"
 	sdk "github.com/cosmos/cosmos-sdk/types"
```
Comment (h5law) [inline x/supplier/keeper/claim.go:8]:
```suggestion
	sdk "github.com/cosmos/cosmos-sdk/types"
	
```

File: x/supplier/client/cli/helpers_test.go [hunk 11]
```diff
@@ -17,8 +17,6 @@ import (
 	"github.com/cosmos/cosmos-sdk/crypto/keyring"
 	testcli "github.com/cosmos/cosmos-sdk/testutil/cli"
 	sdktypes "github.com/cosmos/cosmos-sdk/types"
```
Comment (h5law) [inline x/supplier/client/cli/helpers_test.go:19]:
```suggestion
	sdktypes "github.com/cosmos/cosmos-sdk/types"
	
```

File: x/session/keeper/session_hydrator.go [hunk 12]
```diff
@@ -9,11 +9,10 @@ import (
 
 	sdkerrors "cosmossdk.io/errors"
 	sdk "github.com/cosmos/cosmos-sdk/types"
```
Comment (h5law) [inline x/session/keeper/session_hydrator.go:11]:
```suggestion
	sdk "github.com/cosmos/cosmos-sdk/types"
	
```

File: x/gateway/keeper/msg_server_unstake_gateway.go [hunk 13]
```diff
@@ -2,9 +2,9 @@ package keeper
 
 import (
 	"context"
+	"fmt"
 
 	sdk "github.com/cosmos/cosmos-sdk/types"
```
Comment (h5law) [inline x/gateway/keeper/msg_server_unstake_gateway.go:7]:
```suggestion
	sdk "github.com/cosmos/cosmos-sdk/types"
	
```

File: x/gateway/keeper/msg_server_stake_gateway.go [hunk 14]
```diff
@@ -2,10 +2,10 @@ package keeper
 
 import (
 	"context"
+	"fmt"
 
 	sdkerrors "cosmossdk.io/errors"
 	sdk "github.com/cosmos/cosmos-sdk/types"
```
Comment (h5law) [inline x/gateway/keeper/msg_server_stake_gateway.go:8]:
```suggestion
	sdk "github.com/cosmos/cosmos-sdk/types"
	
```

File: x/application/keeper/msg_server_unstake_application.go [hunk 15]
```diff
@@ -2,9 +2,9 @@ package keeper
 
 import (
 	"context"
+	"fmt"
 
 	sdk "github.com/cosmos/cosmos-sdk/types"
```
Comment (h5law) [inline x/application/keeper/msg_server_unstake_application.go:7]:
```suggestion
	sdk "github.com/cosmos/cosmos-sdk/types"
	
```

File: x/application/keeper/msg_server_undelegate_from_gateway_test.go [hunk 16]
```diff
@@ -5,13 +5,12 @@ import (
 	"testing"
 
 	sdk "github.com/cosmos/cosmos-sdk/types"
```
Comment (h5law) [inline x/application/keeper/msg_server_undelegate_from_gateway_test.go:7]:
```suggestion
	sdk "github.com/cosmos/cosmos-sdk/types"
	
```

File: x/application/keeper/msg_server_undelegate_from_gateway.go [hunk 17]
```diff
@@ -2,10 +2,10 @@ package keeper
 
 import (
 	"context"
+	"fmt"
 
 	sdkerrors "cosmossdk.io/errors"
 	sdk "github.com/cosmos/cosmos-sdk/types"
```
Comment (h5law) [inline x/application/keeper/msg_server_undelegate_from_gateway.go:8]:
```suggestion
	sdk "github.com/cosmos/cosmos-sdk/types"
	
```

File: x/application/keeper/msg_server_delegate_to_gateway_test.go [hunk 18]
```diff
@@ -5,13 +5,12 @@ import (
 	"testing"
 
 	sdk "github.com/cosmos/cosmos-sdk/types"
```
Comment (h5law) [inline x/application/keeper/msg_server_delegate_to_gateway_test.go:7]:
```suggestion
	sdk "github.com/cosmos/cosmos-sdk/types"

```

File: x/application/keeper/msg_server_delegate_to_gateway.go [hunk 19]
```diff
@@ -2,64 +2,64 @@ package keeper
 
 import (
 	"context"
+	"fmt"
 
 	sdkerrors "cosmossdk.io/errors"
 	sdk "github.com/cosmos/cosmos-sdk/types"
```
Comment (h5law) [inline x/application/keeper/msg_server_delegate_to_gateway.go:8]:
```suggestion
	sdk "github.com/cosmos/cosmos-sdk/types"

```

**Review by h5law — CHANGES_REQUESTED** [review]
I suggest running `goimports-reviser` sorry for the barrage of comments lmao. `goimports` doesn't differentiate external and internal imports just stdlib and everything else

**Comment by bryanchriswhite** [comment]
> I suggest running `goimports-reviser` sorry for the barrage of comments lmao. `goimports` doesn't differentiate external and internal imports just stdlib and everything else. With `goimports-reviser` we get the 3 distinct groups we want.

:thinking: Since we have an initial golangci-lint setup, it seems like reaching  for `gci` to address this might be the lowest effort approach. See [this conversation with chatGPT](https://chat.openai.com/share/93914e04-4a18-401f-adb2-58fd06dc2434).

File: pkg/client/supplier/client.go [hunk 20]
```diff
@@ -66,6 +66,8 @@ func (sClient *supplierClient) SubmitProof(
 	sessionHeader sessiontypes.SessionHeader,
 	proof *smt.SparseMerkleClosestProof,
 ) error {
+	logger := polylog.Ctx(ctx)
```
[the remark this answers is not in the document]
Comment (bryanchriswhite) [reply pkg/client/supplier/client.go:69]: @Olshansk this should be fixed by #260.

File: e2e/tests/relay.feature [hunk 21]
```diff
@@ -1,5 +1,6 @@
 Feature: Relay Namespace
 
+    # TODO_TECHDEBT(@Olshansk, #180): This test requires you to run `make supplier1_stake && make app1_stake` first
```
Comment (bryanchriswhite) [inline e2e/tests/relay.feature:3]: For the purposes of the E2E test, we also have the option to shortcut #180 by modifying existing step definitions (e.g. `#TheApplicationIsStakedForService`), or adding new step(s) (i.e. "given ..."),  which do this staking against local/dev-net

File: e2e/tests/session_steps_test.go [hunk 22]
```diff
@@ -11,20 +11,19 @@ import (
...
 )
 
 const (
 	createClaimTimeoutDuration   = 10 * time.Second
 	eitherEventsReplayBufferSize = 100
-	msgClaimSenderQueryFmt       = "tm.event='Tx' AND message.sender='%s'"
+	msgClaimSenderQueryFmt       = "tm.event='Tx' AND message.sender='%s' AND message.action='/pocket.supplier.MsgCreateClaim'"
```
Comment (bryanchriswhite) [inline e2e/tests/session_steps_test.go:26]: Ty for adding this back, it got lost while debugging. :sweat_smile:

File: e2e/tests/session_steps_test.go [hunk 23]
```diff
@@ -86,17 +85,21 @@ func (s *suite) AfterTheSupplierCreatesAClaimForTheSessionForServiceForApplicati
...
+	require.NotNil(s, allClaimsRes)
 
 	// Assert that the number of claims has increased by one.
 	preExistingClaims := s.scenarioState[preExistingClaimsKey].([]suppliertypes.Claim)
-	require.Len(s, claimsRes.Claim, len(preExistingClaims)+1)
+	// NB: We are avoiding the use of require.Len here because it provides unreadable output
+	// TODO_TECHDEBT: Due to the speed of the blocks of the LocalNet sequencer, along with the small number
+	// of blocks per session, multiple claims may be created throughout the duration of the test. Until
+	// these values are appropriately adjusted
+	require.Greater(s, len(allClaimsRes.Claim), len(preExistingClaims), "number of claims must have increased")
```
Comment (bryanchriswhite) [inline e2e/tests/session_steps_test.go:102]: I think `require.Greater()` works better here in general. :100: 

I'm not so convinced that the comment against usage of `require.Len()`  is warranted, did you experiment with `require.Lenf()`?

File: localnet/kubernetes/values-relayminer.yaml [hunk 24]
```diff
@@ -1,4 +1,3 @@
 config:
   query_node_url: tcp://sequencer-poktroll-sequencer:36657
   network_node_url: tcp://sequencer-poktroll-sequencer:36657
-
```
Comment (bryanchriswhite) [inline localnet/kubernetes/values-relayminer.yaml:4]: Is this change intentional or automatic (IDE)? I think we should prefer trailing new-lines in our files.

File: pkg/client/delegation/client.go [hunk 25]
```diff
@@ -15,11 +14,11 @@ const (
 	// See: https://docs.cosmos.network/v0.47/learn/advanced/events#subscribing-to-events
 	// And: https://docs.cosmos.network/v0.47/learn/advanced/events#default-events
 	delegationEventQuery = "message.action='pocket.application.EventRedelegation'"
-	// TODO_TECHDEBT/TODO_FUTURE: add a `blocksReplayLimit` field to the block
-	// client struct that defaults to this but can be overridden via an option
-	// in future work.
+
 	// defaultRedelegationsReplayLimit is the number of redelegations that the
 	// replay observable returned by LastNRedelegations() will be able to replay.
+	// TODO_TECHDEBT/TODO_FUTURE: add a `blocksReplayLimit` field to the blockClient
```
Comment (bryanchriswhite) [inline pkg/client/delegation/client.go:20]:
```suggestion
	// TODO_TECHDEBT/TODO_FUTURE: add a `redelegationsReplayLimit` field to the `delegationClient`
```

File: pkg/client/events/replay_client_example_test.go [hunk 26]
```diff
@@ -6,7 +6,6 @@ import (
 	"fmt"
 
 	"cosmossdk.io/depinject"
-
```
Comment (bryanchriswhite) [inline pkg/client/events/replay_client_example_test.go:9]: NIT (goimports): Pls revert

File: pkg/client/events/replay_client_example_test.go [hunk 27]
```diff
@@ -23,6 +22,8 @@ const (
 	replayObsBufferSize = 1
 )
 
+var _ EventType = (*eventType)(nil)
```
Comment (bryanchriswhite) [inline pkg/client/events/replay_client_example_test.go:25]: :ok_hand:

File: pkg/client/interface.go [hunk 28]
```diff
@@ -21,13 +21,12 @@ import (
...
 	cosmostypes "github.com/cosmos/cosmos-sdk/types"
 	accounttypes "github.com/cosmos/cosmos-sdk/x/auth/types"
-	"github.com/pokt-network/smt"
-
 	"github.com/pokt-network/poktroll/pkg/either"
 	"github.com/pokt-network/poktroll/pkg/observable"
 	apptypes "github.com/pokt-network/poktroll/x/application/types"
 	sessiontypes "github.com/pokt-network/poktroll/x/session/types"
 	sharedtypes "github.com/pokt-network/poktroll/x/shared/types"
+	"github.com/pokt-network/smt"
```
Comment (bryanchriswhite) [inline pkg/client/interface.go:29]: NIT (goimports)

File: pkg/client/supplier/client.go [hunk 29]
```diff
@@ -5,12 +5,12 @@ import (
...
 	"cosmossdk.io/depinject"
 	cosmostypes "github.com/cosmos/cosmos-sdk/types"
-	"github.com/pokt-network/smt"
-
 	"github.com/pokt-network/poktroll/pkg/client"
 	"github.com/pokt-network/poktroll/pkg/client/keyring"
+	"github.com/pokt-network/poktroll/pkg/polylog"
 	sessiontypes "github.com/pokt-network/poktroll/x/session/types"
 	suppliertypes "github.com/pokt-network/poktroll/x/supplier/types"
+	"github.com/pokt-network/smt"
```
Comment (bryanchriswhite) [inline pkg/client/supplier/client.go:13]: NIT (goimports)

File: pkg/client/supplier/client.go [hunk 30]
```diff
@@ -82,6 +84,14 @@ func (sClient *supplierClient) SubmitProof(
 		return err
 	}
 
+	// TODO_IMPROVE: log details related to what & how much is being proven
+	logger.Info().
+		Str("supplier_addr", sClient.signingKeyAddr.String()).
+		Str("app_addr", sessionHeader.ApplicationAddress).
+		Str("session_id", sessionHeader.SessionId).
+		Str("service", sessionHeader.Service.Id).
+		Msg("created a new proof")
```
Comment (bryanchriswhite) [inline pkg/client/supplier/client.go:93]: With so many fields, it may improve readability and maintainability to use `#Fields()` instead:

```suggestion
	logger.Info().
		Fields(map[string]any{
				"supplier_addr": sClient.signingKeyAddr.String(),
				"app_addr": sessionHeader.ApplicationAddress,
				"session_id": sessionHeader.SessionId,
				"service": sessionHeader.Service.Id,
		}).
		Msg("created a new proof")

File: pkg/client/supplier/client_test.go [hunk 31]
```diff
@@ -76,7 +76,7 @@ func TestSupplierClient_CreateClaim(t *testing.T) {
 	var (
 		signAndBroadcastDelay = 50 * time.Millisecond
 		doneCh                = make(chan struct{}, 1)
-		ctx                   = context.Background()
+		ctx                   = polyzero.NewLogger().WithContext(context.Background())
```
Comment (bryanchriswhite) [inline pkg/client/supplier/client_test.go:79]: This shouldn't be strictly necessary as `polylog.Ctx()` will use the polyzero logger by default if one has not been provided to the context. IIRC other  tests do not set up loggers but use this default instead.

File: pkg/client/supplier/client_test.go [hunk 32]
```diff
@@ -132,7 +135,7 @@ func TestSupplierClient_SubmitProof(t *testing.T) {
...
```
Comment (bryanchriswhite) [inline pkg/client/supplier/client_test.go:138]: (same as https://github.com/pokt-network/poktroll/pull/253#discussion_r1423735569)

File: pkg/relayer/relayminer_test.go [hunk 33]
```diff
@@ -6,13 +6,12 @@ import (
...
 
 	"cosmossdk.io/depinject"
-	"github.com/stretchr/testify/require"
-
 	"github.com/pokt-network/poktroll/pkg/observable/channel"
 	"github.com/pokt-network/poktroll/pkg/polylog/polyzero"
 	"github.com/pokt-network/poktroll/pkg/relayer"
 	"github.com/pokt-network/poktroll/testutil/testrelayer"
 	servicetypes "github.com/pokt-network/poktroll/x/service/types"
+	"github.com/stretchr/testify/require"
```
Comment (bryanchriswhite) [inline pkg/relayer/relayminer_test.go:14]: NIT (goimports)

Comment (bryanchriswhite) [reply pkg/relayer/relayminer_test.go:14]: There are more.. stopping here to reduce the comment count.

File: pkg/client/supplier/client_test.go [hunk 34]
```diff
@@ -157,6 +160,9 @@ func TestSupplierClient_SubmitProof(t *testing.T) {
 		ApplicationAddress:      testAppAddr.String(),
 		SessionStartBlockHeight: 0,
 		SessionId:               "",
+		Service: &sharedtypes.Service{
+			Id: "test_service",
```
Comment (bryanchriswhite) [inline pkg/client/supplier/client_test.go:164]: Is there already a constant for this?

File: testutil/network/network.go [hunk 35]
```diff
@@ -101,6 +100,9 @@ func DefaultConfig() network.Config {
 	}
 }
 
+// TODO_CLEANUP: Refactor the genesis state helpers below to consolidate usage
+// and reduce the code footprint.
```
Comment (bryanchriswhite) [inline testutil/network/network.go:104]: I'm working on this right now (related to #141).

File: testutil/testclient/localnet.go [hunk 36]
```diff
@@ -1,37 +1,39 @@
...
 
 // init initializes the SDK configuration upon package import.
 func init() {
 	cmd.InitSDKConfig()
+
+	// If SEQUENCER_RPC_ENDPOINT environment variable is set, use it to override the default localnet endpoint.
+	if endpoint := os.Getenv("SEQUENCER_RPC_ENDPOINT"); endpoint != "" {
+		CometLocalTCPURL = fmt.Sprintf("tcp://%s", endpoint)
+		CometLocalWebsocketURL = fmt.Sprintf("ws://%s/websocket", endpoint)
+	}
```
Comment (bryanchriswhite) [inline testutil/testclient/localnet.go:36]: :sunglasses: Nice! :pray:

File: x/application/keeper/msg_server_delegate_to_gateway.go [hunk 37]
```diff
@@ -2,64 +2,64 @@ package keeper
...
-
 	"github.com/pokt-network/poktroll/x/application/types"
 )
 
 func (k msgServer) DelegateToGateway(goCtx context.Context, msg *types.MsgDelegateToGateway) (*types.MsgDelegateToGatewayResponse, error) {
 	ctx := sdk.UnwrapSDKContext(goCtx)
 
 	logger := k.Logger(ctx).With("method", "DelegateToGateway")
-	logger.Info("About to delegate application to gateway with msg: %v", msg)
+	logger.Info(fmt.Sprintf("About to delegate application to gateway with msg: %v", msg))
```
Comment (bryanchriswhite) [inline x/application/keeper/msg_server_delegate_to_gateway.go:16]: Perhaps we should consider adding a polylog implementation that wraps the cosmos-sdk logger. :thinking: This is kinda gross to ready by comparison.

Comment (bryanchriswhite) [reply x/application/keeper/msg_server_delegate_to_gateway.go:16]: @Olshansk can you elaborate on the need for this change, was the logger not treating the first arg like a format string?

**Review by bryanchriswhite — COMMENTED** [review]
image

File: e2e/tests/session_steps_test.go (hunk 23 above)
Comment (Olshansk) [reply e2e/tests/session_steps_test.go:102]: > I think require.Greater() works better here in general and the part of the comment explaining this assertion is 👌. 💯

👍 

> I'm less convinced that the part of the comment against usage of require.Len() is warranted, did you experiment with require.Lenf()?

I did experiment with `Lenf`, but I did experiment with giving `require.Len` an unformatted string.

When there's an error, it prints out the entire claims slice. This was an array of serialized protos and large in length, which looked incomprehensible on the screen and confusing to the reader.

File: localnet/kubernetes/values-relayminer.yaml (hunk 24 above)
Comment (Olshansk) [reply localnet/kubernetes/values-relayminer.yaml:4]: Should be back.

File: e2e/tests/relay.feature (hunk 21 above)
Comment (Olshansk) [reply e2e/tests/relay.feature:3]: Updating the comment but want to keep the actual change outside the scope of this PR.

File: x/application/keeper/msg_server_delegate_to_gateway.go (hunk 37 above)
Comment (Olshansk) [reply x/application/keeper/msg_server_delegate_to_gateway.go:17]: > Perhaps we should consider adding a polylog implementation that wraps the cosmos-sdk logger. 🤔 This is kinda gross to ready by comparison.

No strong opinion on this. If you believe it'll be beneficial, can you create a ticket and put it on the backlog for a few iterations forward?

**Comment by Olshansk** [comment]
@bryanchriswhite @h5law On the topic of imports.

1. I resolved all import related comments without looking into it (see more details below).
2. I tried to setup `goimports-reviser` but it did not work and opened an issue [here](https://github.com/incu6us/goimports-reviser/issues/147).
3. I ran `make go_imports` locally and am under the assumption it should solve what we need.
4. If `make go_imports` does not fix issues introduced by my IDE, I suggest the following (in a followup PR):
- Update `go_imports`
- A PR that updates the imports
- Document suggested import configs for `poktroll developers`

Please lmk if anything import-related is still blocking this PR.

File: e2e/tests/node.go [hunk 38]
```diff
@@ -118,9 +118,9 @@ func (p *pocketdBin) runCurlPostCmd(rpcUrl string, service string, data string,
 	dataStr := fmt.Sprintf("%s", data)
 	urlStr := fmt.Sprintf("%s/%s", rpcUrl, service)
 	base := []string{
-		"-v",                                   // verbose output
-		"-sS",                                  // silent with error
-		"POST",                                 // HTTP method
+		"-v",         // verbose output
+		"-sS",        // silent with error
+		"-X", "POST", // HTTP method
```
[the remark this answers is not in the document]
Comment (okdas) [reply e2e/tests/node.go:123]: @bryanchriswhite ha, thanks for explanation. I added `-X` back because e2e tests were failing on my machine without that argument.

[the remark this answers is not in the document]
Comment (Olshansk) [reply e2e/tests/node.go:123]: TIL  - thank you for GPTing so I don't have to!

File: x/application/keeper/msg_server_delegate_to_gateway.go (hunk 37 above)
Comment (Olshansk) [reply x/application/keeper/msg_server_delegate_to_gateway.go:17]: > can you elaborate on the need for this change, was the logger not treating the first arg like a format string?

I created this diff for example purposes:

```diff
-       logger.Info(fmt.Sprintf("inserted claim for supplier %s with primaryKey %s", claim.SupplierAddress, primaryKey))
+       logger.Info("inserted claim for supplier %s with primaryKey %s", claim.SupplierAddress, primaryKey)
+       // logger.Info(fmt.Sprintf("inserted claim for supplier %s with primaryKey %s", claim.SupplierAddress, primaryKey))
```

Before:

```bash
9:38PM INF inserted claim for supplier pokt19a3t4yunp0dlpfjrp7qwnzwlrzd5fzs2gjaaaj with primaryKey 5f84503087b3159ba59d7fbaaa3a1cfd5a9603e384054d35ca0effa0ccd616d7/pokt19a3t4yunp0dlpfjrp7qwnzwlrzd5fzs2gjaaaj/ method=InsertClaim module=x/supplier
```

After:
```bash
9:53PM INF inserted claim for supplier %s with primaryKey %s method=InsertClaim module=x/supplier pokt19a3t4yunp0dlpfjrp7qwnzwlrzd5fzs2gjaaaj=bd3efa3825a303fee8ceef27280483da31f9073f50766ccfd10257c292bc94a7/pokt19a3t4yunp0dlpfjrp7qwnzwlrzd5fzs2gjaaaj/
9:53PM INF indexed claim for supplier pokt19a3t4yunp0dlpfjrp7qwnzwlrzd5fzs2gjaaaj with primaryKey bd3efa3825a303fee8ceef27280483da31f9073f50766ccfd10257c292bc94a7/pokt19a3t4yunp0dlpfjrp7qwnzwlrzd5fzs2gjaaaj/ method=InsertClaim module=x/supplier
9:53PM INF indexed claim for supplier pokt19a3t4yunp0dlpfjrp7qwnzwlrzd5fzs2gjaaaj at session ending height 32 method=InsertClaim module=x/supplier
```

Comment (Olshansk) [reply x/application/keeper/msg_server_delegate_to_gateway.go:17]: Adding a screenshot as an extra datapoint. Note that the `keypals` in Cosmos' `logger.Info` are not msg formatting args, but actual `key=value` params added at the end.


Screenshot 2023-12-12 at 2 03 06 PM

**Comment by Olshansk** [comment]
@bryanchriswhite @h5law Please see my comment above regarding imports. I've re-validated that `make go_test` and `make test_e2e` work, and checking here now if it also works in devnet.

@okdas Can you please verify [this change](https://github.com/pokt-network/poktroll/pull/253/commits/69f9a9efb21633665e57c7d47f9fec05f49ca6ad). I believe this was an artifact that's no longer necessary (@red-0ne and I discovered it yesterday) but would appreciate another set of 👀 .

File: pkg/relayer/relayminer_test.go (hunk 33 above)
Comment (h5law) [inline pkg/relayer/relayminer_test.go:14]: Missed this file

File: testutil/testclient/localnet.go [hunk 39]
```diff
@@ -12,26 +15,26 @@ import (
...
 )
 
-const (
+var (
 	// CometLocalTCPURL provides a default URL pointing to the localnet TCP endpoint.
-	//
-	// TODO_IMPROVE: It would be nice if the value could be set correctly based
-	// on whether the test using it is running in tilt or not.
-	CometLocalTCPURL = "tcp://sequencer-poktroll-sequencer:36657"
+	CometLocalTCPURL = "tcp://localhost:36657"
```
Comment (h5law) [inline testutil/testclient/localnet.go:20]: 🔥

File: x/application/keeper/msg_server_delegate_to_gateway_test.go (hunk 4 above)
Comment (h5law) [inline x/application/keeper/msg_server_delegate_to_gateway_test.go:13]: Bump

File: x/application/keeper/msg_server_undelegate_from_gateway_test.go (hunk 5 above)
Comment (h5law) [inline x/application/keeper/msg_server_undelegate_from_gateway_test.go:13]: Bump

File: x/supplier/client/cli/helpers_test.go (hunk 7 above)
Comment (h5law) [inline x/supplier/client/cli/helpers_test.go:28]: Bump

**Review by h5law — APPROVED** [review]
LGTM few files to `goimports-reviser` left but approving so we can merge <3

**Comment by Olshansk** [comment]
@h5law See the comment I left [here](https://github.com/pokt-network/poktroll/pull/253#issuecomment-1852842935) regarding imports. I'll make the manual changes suggested, but can you look into why `tools/scripts/imports/main.go` (executed via make go_imports) doesn't fix it.

**Comment by bryanchriswhite** [comment]
> @bryanchriswhite @h5law On the topic of imports.
> 
> 1. I resolved all import related comments without looking into it (see more details below).
> 2. I tried to setup `goimports-reviser` but it did not work and opened an issue [here](https://github.com/incu6us/goimports-reviser/issues/147).
> 3. I ran `make go_imports` locally and am under the assumption it should solve what we need.
> 4. If `make go_imports` does not fix issues introduced by my IDE, I suggest the following (in a followup PR):
> 
> * Update `go_imports`
> * A PR that updates the imports
> * Document suggested import configs for `poktroll developers`
> 
> Please lmk if anything import-related is still blocking this PR.

[BUMP](https://github.com/pokt-network/poktroll/pull/253#issuecomment-1851548350):
image

File: localnet/kubernetes/values-relayminer.yaml (hunk 24 above)
Comment (bryanchriswhite) [reply localnet/kubernetes/values-relayminer.yaml:4]: Doesn't look like it. Did you `git checkout main -- localnet/kubernetes/values-relayminer.yaml`?

Comment (bryanchriswhite) [reply localnet/kubernetes/values-relayminer.yaml:4]: Doesn't look like it. Did you `git checkout main -- localnet/kubernetes/values-relayminer.yaml`?

File: e2e/tests/session_steps_test.go (hunk 23 above)
Comment (bryanchriswhite) [reply e2e/tests/session_steps_test.go:102]: I did experiment with Lenf, but I did experiment with giving require.Len an unformatted string.

I'm assuming one of those is suppose to be a "didn't". :sweat_smile: 

---

For the record, in other  cases, I would argue that `#Lenf()` produces the least ambiguous output. I agree that the output can be large if the list is not empty; however, that information is useful when debugging, and isn't obscuring the reason for failure as it's on its own line.

### `#Lenf()`
```go
func TestSanity(t *testing.T) {
	x := []struct{ a, b int }{{1, 2}, {3, 4}}
	require.Lenf(t, x, 3, "x should have 3 elements, got %d", len(x))
}
```
image

### `#Len()`
```go
func TestSanity(t *testing.T) {
	x := []struct{ a, b int }{{1, 2}, {3, 4}}
	require.Len(t, x, 3)
}
```
image

### `#Greater()`
```go
func TestSanity(t *testing.T) {
	x := []struct{ a, b int }{{1, 2}, {3, 4}}
	require.Greater(t, len(x), 2)
}
```
image

File: pkg/client/supplier/client.go [hunk 40]
```diff
@@ -82,6 +85,16 @@ func (sClient *supplierClient) SubmitProof(
...
 	}
 
+	// TODO_IMPROVE: log details related to what & how much is being proven
+	logger.Info().
+		Fields(map[string]any{
+			"supplier_addr": sClient.signingKeyAddr.String(),
+			"app_addr":      sessionHeader.ApplicationAddress,
+			"session_id":    sessionHeader.SessionId,
+			"service":       sessionHeader.Service.Id,
+		}).
```
Comment (bryanchriswhite) [inline pkg/client/supplier/client.go:95]: It looks like the same map literal is being declared twice for logging purposes. Perhaps it would be convenient to assign it to a variable instead (here and line 124)?

**Review by bryanchriswhite — CHANGES_REQUESTED** [review]
I had a couple of NITs but otherwise let's :ship:

File: pkg/client/supplier/client.go (hunk 40 above)
Comment (Olshansk) [reply pkg/client/supplier/client.go:95]: One of the them is being assigned in the `CreateClaim` function and the other is being assigned in the `SubmitProof` function.

Both are dependant on the input values provided. 

Can you elaborate on what you had in mind?

Comment (bryanchriswhite) [reply pkg/client/supplier/client.go:95]: Ignore me :upside_down_face:

**Review by bryanchriswhite — APPROVED** [review]
